In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
method='SVM'

In [19]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# Load your data into a Pandas DataFrame
data = pd.read_csv('/content/drive/MyDrive/miniproject/3D_dataset_Authentic/ab.csv')


# Split the data into features and labels
X = data.iloc[:,[1,9,33,89]]  # Assuming 'label' is the name of the column containing the target labels

X.head()

ch1/prn  ch1/cdh  ch1/tow  ch1/tcd
0        0      0.0      0.0      0.0
1        0      0.0      0.0      0.0
2        0      0.0      0.0      0.0
3        0      0.0      0.0      0.0
4        0      0.0      0.0      0.0

In [12]:
y = data.iloc[:,105]
y.head()

0    a0
1    a0
2    a0
3    a0
4    a0
Name: ch1/o, dtype: object

In [7]:


# Perform data normalization using Min-Max scaling
# df =data.drop(0, axis=0)
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Handle missing values by filling them with the mean of the respective column
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X_normalized)

# Convert the preprocessed data back to a DataFrame
X_preprocessed = pd.DataFrame(X_imputed, columns=X.columns)

# Split the preprocessed data into training, validation, and testing sets
X_train, X_val_test, y_train, y_val_test = train_test_split(X_preprocessed, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_val_test, y_val_test, test_size=0.5, random_state=42)

# Now you can use X_train, y_train, X_val, y_val, X_test, y_test as inputs for your KNN model
X_train = X_train.to_numpy()
X_val = X_val.to_numpy()
# Train and evaluate your KNN model
if(method=='KNN'): clf = KNeighborsClassifier(n_neighbors=5)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='RF'): clf = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='DT'): clf = DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='GB'): clf = GaussianNB() # You can adjust the hyperparameter n_neighbors as needed
if(method=='SVM'): clf = LinearSVC(C=1.0, penalty='l2', max_iter=1000)  # You can adjust the hyperparameter n_neighbors as needed

  # You can adjust the hyperparameter n_neighbors as needed
clf.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred = clf.predict(X_val)

# Evaluate the performance of the model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_val, y_val_pred)
precision = precision_score(y_val, y_val_pred, average='weighted')  # Use 'weighted' for multiclass
recall = recall_score(y_val, y_val_pred, average='weighted')  # Use 'weighted' for multiclass
f1 = f1_score(y_val, y_val_pred, average='weighted')  
# You can also perform hyperparameter tuning, model interpretability, and other model evaluation tasks as needed

# Once you have finalized your model, you can use it for inference on new, unseen data

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
y.unique()


array(['a0', 'a1', 'a3', 'a2'], dtype=object)

In [20]:
from sklearn.model_selection import ShuffleSplit
kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
X = scaler.fit_transform(X)
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
pca = PCA(n_components=2)

# Fit the data to the PCA model
pca.fit(X)

# Transform the data to the principal components
transformed_data = pca.transform(X)
knn = cross_val_score(KNeighborsClassifier(n_neighbors=5),transformed_data,y,cv=kfold_validation)
rf = cross_val_score(RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),transformed_data,y,cv=kfold_validation)
dt = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),transformed_data,y,cv=kfold_validation)
gb = cross_val_score(GaussianNB(),transformed_data,y,cv=kfold_validation) # You can adjust the hyperparameter n_neighbors as needed
svm = cross_val_score(LinearSVC(C=1.0, penalty='l2', max_iter=1000),transformed_data,y,cv=kfold_validation)
print(np.mean(knn))

print(np.mean(rf))

print(np.mean(dt))

print(np.mean(gb))

print(np.mean(svm))



0.9162076159568414
0.9063241523191369
0.911862263713569
0.8145891724443134
0.8651149558510527


In [15]:

import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif

# # Sample data
# X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Input features
# y = np.array([0, 1, 0])  # Target variable

# # Instantiate SelectKBest with ANOVA F-value scoring
selector = SelectKBest(score_func=f_classif, k=4) 

# Fit the data to the selector
X_new = selector.fit_transform(X, y)

# Get the indices of the selected features
selected_feature_indices = selector.get_support(indices=True)

# Print the selected feature indices and scores
print("Selected Feature Indices:")
print(X_new)
print(selected_feature_indices)
print("\nFeature Scores:")
print(selector.scores_)

Selected Feature Indices:
[[0.         0.32589512 0.         0.24996563]
 [0.         0.32589512 0.         0.24996563]
 [0.         0.32589512 0.         0.24996563]
 ...
 [0.16       0.18976174 0.5368107  0.09103378]
 [0.16       0.18941989 0.53681074 0.09230811]
 [0.16       0.18925064 0.53681078 0.09276743]]
[ 0  1  4 11]

Feature Scores:
[1.30634435e+04 9.62660949e+03 3.68472974e+03 5.04052395e+03
 9.16153245e+03 6.33976500e+03 6.14069407e+03 6.13028993e+03
 6.12016372e+03 1.93339597e+00 4.84616563e+00 9.39948047e+03
 8.40526641e+03]


In [17]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
X = scaler.fit_transform(X)

kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)

knn = cross_val_score(KNeighborsClassifier(n_neighbors=5),X,y,cv=kfold_validation)
rf = cross_val_score(RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),X,y,cv=kfold_validation)
dt = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),X,y,cv=kfold_validation)
gb = cross_val_score(GaussianNB(),X,y,cv=kfold_validation) # You can adjust the hyperparameter n_neighbors as needed
svm = cross_val_score(LinearSVC(C=1.0, penalty='l2', max_iter=1000),X,y,cv=kfold_validation)


print( np.mean(knn))

print( np.mean(rf))

print( np.mean(dt))

print( np.mean(gb))

print(np.mean(svm))

0.9103323288306324
0.9242808673845702
0.9342085853370703
0.8553726845510294
0.874366214991676


In [ ]:
print(f'Accuracy: {accuracy}')
print(f'precision: {precision}')
print(f'recall: {recall}')
print(f'f1: {f1}')

Accuracy: 0.8841355475006322
precision: 0.8712453141140684
recall: 0.8841355475006322
f1: 0.8437456492549357


In [ ]:
!pip install joblib
from joblib import dump
dump(clf,'/content/drive/MyDrive/miniproject/one.joblib')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


['/content/drive/MyDrive/miniproject/one.joblib']

In [ ]:
from sklearn.model_selection import ShuffleSplit
kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
scaler = MinMaxScaler()
X = X.to_numpy()
X = scaler.fit_transform(X)

In [ ]:
results = cross_val_score(clf,X,y,cv=kfold_validation)

In [ ]:
print(results)
print(np.mean(results))

[0.88736223 0.88780478 0.88753082 0.88430658 0.88632963 0.88689862
 0.88582387 0.88432765 0.88761511 0.88595031]
0.88639495922281
