In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
method='SVM'

In [14]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# Load your data into a Pandas DataFrame
data = pd.read_csv('/content/drive/MyDrive/miniproject/3D_dataset_Authentic/ab.csv')


# Split the data into features and labels
X = data.iloc[:,[18,50,66,98]]  # Assuming 'label' is the name of the column containing the target labels

print(X)

           ch2/psrn       ch2/ec       ch2/pc    ch2/cn0
0             0.000       0.0000       0.0000   0.000000
1             0.000       0.0000       0.0000   0.000000
2             0.000       0.0000       0.0000   0.000000
3             0.000       0.0000       0.0000   0.000000
4             0.000       0.0000       0.0000   0.000000
...             ...          ...          ...        ...
158170  2823811.429  114627.0000  132859.9375  46.471382
158171  2823798.215  112431.8438  130385.7734  46.537384
158172  2823784.769  129567.5703  153883.7813  46.470272
158173  2823771.385  127447.3203  148744.4219  46.359314
158174  2823757.974  107531.3516  123142.2969  46.334122

[158175 rows x 4 columns]


In [15]:
y = data.iloc[:,106]
y.head()


0    b0
1    b0
2    b0
3    b0
4    b0
Name: ch2/o, dtype: object

In [ ]:
y.unique()

array(['b0', 'b1'], dtype=object)

In [ ]:


# Perform data normalization using Min-Max scaling
# df =data.drop(0, axis=0)
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Handle missing values by filling them with the mean of the respective column
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X_normalized)

# Convert the preprocessed data back to a DataFrame
X_preprocessed = pd.DataFrame(X_imputed, columns=X.columns)

# Split the preprocessed data into training, validation, and testing sets
X_train, X_val_test, y_train, y_val_test = train_test_split(X_preprocessed, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_val_test, y_val_test, test_size=0.5, random_state=42)
X_train = X_train.to_numpy()
X_val = X_val.to_numpy()
# Now you can use X_train, y_train, X_val, y_val, X_test, y_test as inputs for your KNN model

# Train and evaluate your KNN model
if(method=='KNN'): clf = KNeighborsClassifier(n_neighbors=5)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='RF'): clf = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='DT'): clf = DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='GB'): clf = GaussianNB() # You can adjust the hyperparameter n_neighbors as needed
if(method=='SVM'): clf = LinearSVC(C=1.0, penalty='l2', max_iter=1000)  # You can adjust the hyperparameter n_neighbors as needed

  # You can adjust the hyperparameter n_neighbors as needed
clf.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred = clf.predict(X_val)

# Evaluate the performance of the model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_val, y_val_pred)
precision = precision_score(y_val, y_val_pred, average='weighted')  # Use 'weighted' for multiclass
recall = recall_score(y_val, y_val_pred, average='weighted')  # Use 'weighted' for multiclass
f1 = f1_score(y_val, y_val_pred, average='weighted')  
# You can also perform hyperparameter tuning, model interpretability, and other model evaluation tasks as needed

# Once you have finalized your model, you can use it for inference on new, unseen data

In [ ]:
y.unique()


array(['b0', 'b1'], dtype=object)

In [ ]:
print(f'Accuracy: {accuracy}')
print(f'precision: {precision}')
print(f'recall: {recall}')
print(f'f1: {f1}')

Accuracy: 0.7189581050324538
precision: 0.9675638871346774
recall: 0.7189581050324538
f1: 0.8070030258311166


In [ ]:
!pip install joblib
from joblib import dump
dump(clf,'/content/drive/MyDrive/miniproject/two.joblib')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


['/content/drive/MyDrive/miniproject/two.joblib']

In [6]:
from sklearn.model_selection import ShuffleSplit
kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
X = scaler.fit_transform(X)
results = cross_val_score(clf,X,y,cv=kfold_validation)
print(results)
print(np.mean(results))

NameError: ignored

In [9]:
from sklearn.model_selection import ShuffleSplit
kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
X = scaler.fit_transform(X)
pca = PCA(n_components=2)

# Fit the data to the PCA model
pca.fit(X)

# Transform the data to the principal components
transformed_data = pca.transform(X)
knn = cross_val_score(KNeighborsClassifier(n_neighbors=5),transformed_data,y,cv=kfold_validation)
rf = cross_val_score(RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),transformed_data,y,cv=kfold_validation)
dt = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),transformed_data,y,cv=kfold_validation)
gb = cross_val_score(GaussianNB(),transformed_data,y,cv=kfold_validation) # You can adjust the hyperparameter n_neighbors as needed
svm = cross_val_score(LinearSVC(C=1.0, penalty='l2', max_iter=1000),transformed_data,y,cv=kfold_validation)
print(np.mean(knn))

print(np.mean(rf))

print(np.mean(dt))

print(np.mean(gb))

print(np.mean(svm))



0.9750216003203169
0.9782416285587845
0.9775925652751143
0.9254546604008176
0.9628390196615599


In [10]:

import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif

# # Sample data
# X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Input features
# y = np.array([0, 1, 0])  # Target variable

# # Instantiate SelectKBest with ANOVA F-value scoring
selector = SelectKBest(score_func=f_classif, k=4) 

# Fit the data to the selector
X_new = selector.fit_transform(X, y)

# Get the indices of the selected features
selected_feature_indices = selector.get_support(indices=True)

# Print the selected feature indices and scores
print("Selected Feature Indices:")
print(X_new)
print(selected_feature_indices)
print("\nFeature Scores:")
print(selector.scores_)

Selected Feature Indices:
[[0.13112596 0.         0.         0.        ]
 [0.13112596 0.         0.         0.        ]
 [0.13112596 0.         0.         0.        ]
 ...
 [0.2177992  0.57322366 0.65232637 0.92472782]
 [0.21779879 0.5638434  0.63054019 0.92251983]
 [0.21779838 0.47573258 0.52201062 0.92201852]]
[ 2  6  8 12]

Feature Scores:
[5.36403425e+03 2.69299891e+03 9.07146290e+03 1.10998774e+02
 2.70220576e+03 6.99070163e+02 8.97233835e+03 8.96398518e+03
 9.02017920e+03 1.88707106e+01 2.05797301e+00 2.84264992e+03
 9.15669548e+03]


In [16]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
X = scaler.fit_transform(X)

kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)

knn = cross_val_score(KNeighborsClassifier(n_neighbors=5),X,y,cv=kfold_validation)
rf = cross_val_score(RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),X,y,cv=kfold_validation)
dt = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),X,y,cv=kfold_validation)
gb = cross_val_score(GaussianNB(),X,y,cv=kfold_validation) # You can adjust the hyperparameter n_neighbors as needed
svm = cross_val_score(LinearSVC(C=1.0, penalty='l2', max_iter=1000),X,y,cv=kfold_validation)


print( np.mean(knn))

print( np.mean(rf))

print( np.mean(dt))

print( np.mean(gb))

print(np.mean(svm))

0.9781657640191348
0.9840642319769035
0.984700651170632
0.715640739257792
0.9626367142224938
