In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
method='SVM'

In [8]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# Load your data into a Pandas DataFrame
data = pd.read_csv('/content/drive/MyDrive/miniproject/3D_dataset_Authentic/cb.csv')


# Split the data into features and labels
X = data.iloc[:,[38,46,62,70]]  # Assuming 'label' is the name of the column containing the target labels

X.head()

0.38  0.46  0.62  0.70
0   0.0   0.0   0.0   0.0
1   0.0   0.0   0.0   0.0
2   0.0   0.0   0.0   0.0
3   0.0   0.0   0.0   0.0
4   0.0   0.0   0.0   0.0

In [10]:
y = data.iloc[:,110]
y.head()


0    f0
1    f0
2    f0
3    f0
4    f0
Name: f0, dtype: object

In [11]:
y.unique()

array(['f0', 'f3', 'f1'], dtype=object)

In [ ]:


# Perform data normalization using Min-Max scaling
# df =data.drop(0, axis=0)
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Handle missing values by filling them with the mean of the respective column
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X_normalized)

# Convert the preprocessed data back to a DataFrame
X_preprocessed = pd.DataFrame(X_imputed, columns=X.columns)

# Split the preprocessed data into training, validation, and testing sets
X_train, X_val_test, y_train, y_val_test = train_test_split(X_preprocessed, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_val_test, y_val_test, test_size=0.5, random_state=42)
X_train = X_train.to_numpy()
X_val = X_val.to_numpy()
# Now you can use X_train, y_train, X_val, y_val, X_test, y_test as inputs for your KNN model

# Train and evaluate your KNN model
if(method=='KNN'): clf = KNeighborsClassifier(n_neighbors=5)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='RF'): clf = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='DT'): clf = DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='GB'): clf = GaussianNB() # You can adjust the hyperparameter n_neighbors as needed
if(method=='SVM'): clf = LinearSVC(C=1.0, penalty='l2', max_iter=1000)  # You can adjust the hyperparameter n_neighbors as needed

  # You can adjust the hyperparameter n_neighbors as needed
clf.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred = clf.predict(X_val)

# Evaluate the performance of the model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_val, y_val_pred)
precision = precision_score(y_val, y_val_pred, average='weighted')  # Use 'weighted' for multiclass
recall = recall_score(y_val, y_val_pred, average='weighted')  # Use 'weighted' for multiclass
f1 = f1_score(y_val, y_val_pred, average='weighted')  
# You can also perform hyperparameter tuning, model interpretability, and other model evaluation tasks as needed

# Once you have finalized your model, you can use it for inference on new, unseen data

In [6]:
from sklearn.model_selection import ShuffleSplit
kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
X = scaler.fit_transform(X)
pca = PCA(n_components=2)

# Fit the data to the PCA model
pca.fit(X)

# Transform the data to the principal components
transformed_data = pca.transform(X)
knn = cross_val_score(KNeighborsClassifier(n_neighbors=5),transformed_data,y,cv=kfold_validation)
rf = cross_val_score(RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),transformed_data,y,cv=kfold_validation)
dt = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),transformed_data,y,cv=kfold_validation)
gb = cross_val_score(GaussianNB(),transformed_data,y,cv=kfold_validation) # You can adjust the hyperparameter n_neighbors as needed
svm = cross_val_score(LinearSVC(C=1.0, penalty='l2', max_iter=1000),transformed_data,y,cv=kfold_validation)
print(np.mean(knn))

print(np.mean(rf))

print(np.mean(dt))

print(np.mean(gb))

print(np.mean(svm))



0.9723452679493395
0.9718500410932922
0.970910163740965
0.9205129285819653
0.9325817124312478


In [7]:

import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif

# # Sample data
# X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Input features
# y = np.array([0, 1, 0])  # Target variable

# # Instantiate SelectKBest with ANOVA F-value scoring
selector = SelectKBest(score_func=f_classif, k=4) 

# Fit the data to the selector
X_new = selector.fit_transform(X, y)

# Get the indices of the selected features
selected_feature_indices = selector.get_support(indices=True)

# Print the selected feature indices and scores
print("Selected Feature Indices:")
print(X_new)
print(selected_feature_indices)
print("\nFeature Scores:")
print(selector.scores_)

Selected Feature Indices:
[[0.         0.84777398 0.         0.        ]
 [0.         0.84777398 0.         0.        ]
 [0.         0.84777398 0.         0.        ]
 ...
 [0.53676528 0.60065212 0.58849854 0.56240558]
 [0.53676532 0.60060592 0.748727   0.73071096]
 [0.53676536 0.60055972 0.75609142 0.80963283]]
[4 5 7 8]

Feature Scores:
[2.71273347e+04 1.49550964e+04 2.24756942e+04 1.58550905e+04
 4.47434526e+04 5.42710443e+04 3.11079852e+04 3.11596261e+04
 3.16034327e+04 3.86691492e+01 2.20951875e+00 1.47428515e+04
 2.78886553e+04]


In [12]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
X = scaler.fit_transform(X)

kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)

knn = cross_val_score(KNeighborsClassifier(n_neighbors=5),X,y,cv=kfold_validation)
rf = cross_val_score(RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),X,y,cv=kfold_validation)
dt = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),X,y,cv=kfold_validation)
gb = cross_val_score(GaussianNB(),X,y,cv=kfold_validation) # You can adjust the hyperparameter n_neighbors as needed
svm = cross_val_score(LinearSVC(C=1.0, penalty='l2', max_iter=1000),X,y,cv=kfold_validation)


print( np.mean(knn))

print( np.mean(rf))

print( np.mean(dt))

print( np.mean(gb))

print(np.mean(svm))

0.9713232040123911
0.9909131140286178
0.9929804227340737
0.85198196109835
0.9376667439361052


In [ ]:
print(f'Accuracy: {accuracy}')
print(f'precision: {precision}')
print(f'recall: {recall}')
print(f'f1: {f1}')

Accuracy: 0.9486217651521538
precision: 0.9466606218805413
recall: 0.9486217651521538
f1: 0.9475036692132198


In [ ]:
!pip install joblib
from joblib import dump
dump(clf,'/content/drive/MyDrive/miniproject/six.joblib')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


['/content/drive/MyDrive/miniproject/six.joblib']

In [ ]:
from sklearn.model_selection import ShuffleSplit
kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
X = scaler.fit_transform(X)
results = cross_val_score(clf,X,y,cv=kfold_validation)
print(results)
print(np.mean(results))

[0.94849641 0.94862285 0.95022443 0.94771669 0.94877036 0.94828567
 0.95016121 0.94902324 0.94716878 0.94780098]
0.9486270625671717
