In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
method='SVM'

In [12]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# Load your data into a Pandas DataFrame
data = pd.read_csv('/content/drive/MyDrive/miniproject/3D_dataset_Authentic/ab.csv')


# Split the data into features and labels
X = data.iloc[:,[5,13,21,93]]  # Assuming 'label' is the name of the column containing the target labels

X.head()

ch5/prn  ch5/cdh  ch5/psrn  ch5/tcd
0        0      0.0       0.0      0.0
1        0      0.0       0.0      0.0
2        0      0.0       0.0      0.0
3        0      0.0       0.0      0.0
4        0      0.0       0.0      0.0

In [13]:
y = data.iloc[:,109]
y.head()


0    e0
1    e0
2    e0
3    e0
4    e0
Name: ch5/o, dtype: object

In [ ]:
y.unique()

array(['e0', 'e3', 'e1'], dtype=object)

ch1/o
0    a0
1    a0
2    a0
3    a0
4    a0

In [ ]:


# Perform data normalization using Min-Max scaling
# df =data.drop(0, axis=0)
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Handle missing values by filling them with the mean of the respective column
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X_normalized)

# Convert the preprocessed data back to a DataFrame
X_preprocessed = pd.DataFrame(X_imputed, columns=X.columns)

# Split the preprocessed data into training, validation, and testing sets
X_train, X_val_test, y_train, y_val_test = train_test_split(X_preprocessed, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_val_test, y_val_test, test_size=0.5, random_state=42)
X_train = X_train.to_numpy()
X_val = X_val.to_numpy()
# Now you can use X_train, y_train, X_val, y_val, X_test, y_test as inputs for your KNN model

# Train and evaluate your KNN model
if(method=='KNN'): clf = KNeighborsClassifier(n_neighbors=5)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='RF'): clf = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='DT'): clf = DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1)  # You can adjust the hyperparameter n_neighbors as needed
if(method=='GB'): clf = GaussianNB() # You can adjust the hyperparameter n_neighbors as needed
if(method=='SVM'): clf = LinearSVC(C=1.0, penalty='l2', max_iter=1000)  # You can adjust the hyperparameter n_neighbors as needed

  # You can adjust the hyperparameter n_neighbors as needed
clf.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred = clf.predict(X_val)

# Evaluate the performance of the model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_val, y_val_pred)
precision = precision_score(y_val, y_val_pred, average='weighted')  # Use 'weighted' for multiclass
recall = recall_score(y_val, y_val_pred, average='weighted')  # Use 'weighted' for multiclass
f1 = f1_score(y_val, y_val_pred, average='weighted')  
# You can also perform hyperparameter tuning, model interpretability, and other model evaluation tasks as needed

# Once you have finalized your model, you can use it for inference on new, unseen data

In [10]:
from sklearn.model_selection import ShuffleSplit
kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
X = scaler.fit_transform(X)
pca = PCA(n_components=2)

# Fit the data to the PCA model
pca.fit(X)

# Transform the data to the principal components
transformed_data = pca.transform(X)
knn = cross_val_score(KNeighborsClassifier(n_neighbors=5),transformed_data,y,cv=kfold_validation)
rf = cross_val_score(RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),transformed_data,y,cv=kfold_validation)
dt = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),transformed_data,y,cv=kfold_validation)
gb = cross_val_score(GaussianNB(),transformed_data,y,cv=kfold_validation) # You can adjust the hyperparameter n_neighbors as needed
svm = cross_val_score(LinearSVC(C=1.0, penalty='l2', max_iter=1000),transformed_data,y,cv=kfold_validation)
print(np.mean(knn))

print(np.mean(rf))

print(np.mean(dt))

print(np.mean(gb))

print(np.mean(svm))



0.9781130803110445
0.977577813836849
0.9771858470486586
0.9356205087138854
0.9377447158240786


In [11]:

import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif

# # Sample data
# X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Input features
# y = np.array([0, 1, 0])  # Target variable

# # Instantiate SelectKBest with ANOVA F-value scoring
selector = SelectKBest(score_func=f_classif, k=4) 

# Fit the data to the selector
X_new = selector.fit_transform(X, y)

# Get the indices of the selected features
selected_feature_indices = selector.get_support(indices=True)

# Print the selected feature indices and scores
print("Selected Feature Indices:")
print(X_new)
print(selected_feature_indices)
print("\nFeature Scores:")
print(selector.scores_)

Selected Feature Indices:
[[0.         0.56186191 0.12597373 0.47769675]
 [0.         0.56186191 0.12597373 0.47769675]
 [0.         0.56186191 0.12597373 0.47769675]
 ...
 [0.34615385 0.82113881 0.16776288 0.99927875]
 [0.34615385 0.82196622 0.16776274 0.99901097]
 [0.34615385 0.82245227 0.1677626  0.99919316]]
[ 0  1  2 11]

Feature Scores:
[1.95330083e+04 3.02782144e+04 9.05365698e+04 2.73424077e+03
 1.12477465e+04 1.36772019e+04 9.27634672e+03 9.31064704e+03
 7.90783641e+03 1.74414242e+01 5.73600298e+01 2.95622176e+04
 1.45764564e+04]


In [14]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
X = scaler.fit_transform(X)

kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)

knn = cross_val_score(KNeighborsClassifier(n_neighbors=5),X,y,cv=kfold_validation)
rf = cross_val_score(RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),X,y,cv=kfold_validation)
dt = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_split=2, min_samples_leaf=1),X,y,cv=kfold_validation)
gb = cross_val_score(GaussianNB(),X,y,cv=kfold_validation) # You can adjust the hyperparameter n_neighbors as needed
svm = cross_val_score(LinearSVC(C=1.0, penalty='l2', max_iter=1000),X,y,cv=kfold_validation)


print( np.mean(knn))

print( np.mean(rf))

print( np.mean(dt))

print( np.mean(gb))

print(np.mean(svm))

0.9911343856025964
0.9960908688597139
0.9967947231997976
0.9321180958000547
0.9300613238362168


In [ ]:
print(f'Accuracy: {accuracy}')
print(f'precision: {precision}')
print(f'recall: {recall}')
print(f'f1: {f1}')

Accuracy: 0.9516985585433702
precision: 0.9513981646358662
recall: 0.9516985585433702
f1: 0.9388033077612983


In [ ]:
!pip install joblib
from joblib import dump
dump(clf,'/content/drive/MyDrive/miniproject/five.joblib')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


['/content/drive/MyDrive/miniproject/five.joblib']

In [ ]:
from sklearn.model_selection import ShuffleSplit
kfold_validation=ShuffleSplit(n_splits=10,test_size=0.3)
from sklearn.model_selection import cross_val_score
scaler = MinMaxScaler()
X = X.to_numpy()
X = scaler.fit_transform(X)
results = cross_val_score(clf,X,y,cv=kfold_validation)
print(results)
print(np.mean(results))

[0.95085664 0.95123596 0.9510463  0.95039302 0.95066698 0.95140455
 0.94936042 0.95336438 0.95330116 0.94959223]
0.9511221629823193
